language: scala
matrix:
  include:
  - jdk: openjdk8
    scala: 2.11.12
    os: linux
    dist: trusty
    env: BINTRAY_PUBLISH=true
  - jdk: openjdk11
    scala: 2.12.8
    os: osx
    env: BINTRAY_PUBLISH=true
script:
- ./scripts/buildViaTravis.sh
env:
  global:
  - secure: EakB0ihwg817KJghs6NJ/C75H138DDDDY7jhnuph+2tbA65InChFEtPT6OBW6N/RWd1QOZRZ3UjUMMHoRshgKNMTeU6F6aZORRlJVbtCLDEyaelhfyjiNPkE6xPL1g/h2JqTv8Hv6eWLe8rbDqArSkefFbFXcvztmoKHbmaCkPg=
  - secure: EWmri8Xn196MLbo+uDqJwHXQU1XlsCz9U1qr3cQ8tYPc3SfNixUQoQZNbBDbXAGpbhY/loM/8P7D2AgGntyuw+eaMFvVBrjbUQLkpIvO/NUeN4+x4TJxv+JrGqPvZX25Qgi/nQKOEWABbReD9WASIoeevRUzu9mPlnHVWkJWax0=
  - secure: ZP6uD798wV7/TAjwdP5Cp39B/MB8eJ3wOjXH0sRQpmxOZN3022pOl1FetwGCbXpAwR9CYoUKH7+p9wiCO0/7K9QNzKoqTYPwJG+V8PjN7LYilKzj+gW/2qy2IRBTObwsVtI6q/rQGqAtrb9nf+9ONfpk2EX40i/R9O/EFVAhAe0=
  - secure: JN8m1aj4D7d3yr9c08Xz/iUW/BAdE/o622hNJOlA2RvJofsxAy4C+ZesSTrpE/HpfmwGv8Gzty/ROhG6UiYI2eRaZ5TC3ul9+tmbguTW2VJHUc7BwCpzGsnZo+mhV9fRwAiBHJnYGb9iCiSSOubjRjio+He0B9I9+JS3Oq4fuBk=
cache:
  directories:
  - $HOME/.sbt
  - $HOME/.ivy2
